name: hrcy
channels:
  - defaults
dependencies:
  - python=3.6.7
  - numpy=1.15.4
  - jupyter=1.0.0
  - pip:
      - pytest==4.0.1
      - pytest-cov==2.6.0
      - black==18.9b0
      - isort==4.3.4
prefix: /home/nightwing/anaconda3/envs/hrcy
